apiVersion: v1
kind: Secret
metadata:
  name: my-dockerhub-secret  # Name of the secret
  namespace: default
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: eyJhdXRocyI6IHsiaHR0cHM6Ly9pbmRleC5kb2NrZXIuaW8vdjEvIjogeyJ1c2VybmFtZSI6ICJpYnJhaGltc2hhYmFhbiIsICJwYXNzd29yZCI6ICJOb2tpYTMwM0FzaGEiLCAiZW1haWwiOiAiZWJyYWhpbV9zaGFiYW4xNkB5YWhvby5jb20ifX19














# # kubectl create secret docker-registry my-dockerhub-secret \
# #   --docker-server=https://index.docker.io/v1/ \
# #   --docker-username=ibrahimshabaan \
# #   --docker-password=Nokia303Asha \
# #   --docker-email=ebrahim_shaban16@yahoo.com
